### ISSUE TITLE
Package Maestro

### ISSUE THREAD

**Issue by mawad-amd** [AMDResearch/intelliperf#38]
We need to package maestro such that we can simply install it with a `pip install maestro`. Possibly via a `toml` file like so:

```toml
[project]
name = "maestro"
version = "0.1.0"
description = "Your project description"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"

# Python dependancies 
dependencies = [
    "guided-tuning @ git+ssh://git@github.com/AARInternal/guided-tuning.git@bar/dev",
    "openai>=1.0.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.logduration]
git = "git@github.com:AARInternal/logduration.git"
branch = "dev"
build_command = """
cmake -DCMAKE_INSTALL_PREFIX=/opt/logduration \
      -DCMAKE_PREFIX_PATH=${ROCM_PATH} \
      -DTRITON_LLVM=/root/.triton/llvm/llvm-ubuntu-x64 \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_VERBOSE_MAKEFILE=ON -S . -B build &&
cmake --build build -j &&
cmake --install build
"""
```

Note that we would need a similar thing for GT but should be less complex.
